# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' } { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)


al = Team.create(map_id: 1, state_code: 'AL', name: 'Alabama', nickname: 'Yellowhammers')
ak = Team.create(map_id: 2, state_code: 'AK', name: 'Alaska', nickname: 'Willow Ptarmigans')

az = Team.create(map_id: 4, state_code: 'AZ', name: 'Arizona', nickname: 'Cactus Wrens', park_image: '/images/parks/az.png')
az.players.create(name: 'Doug Mirabelli', position: 'C', home: 'Kingman', born: '1970', ops: '.723')
az.players.create(name: 'Brian Banks', position: '1B', home: 'Mesa', born: '1970', ops: '.703')
az.players.create(name: 'Ian Kinsler', position: '2B', home: 'Tucson', born: '1982', ops: '.802')
az.players.create(name: 'Shea Hillenbrand', position: '3B', home: 'Mesa', born: '1975', ops: '.760')
az.players.create(name: 'Solly Hemus', position: 'SS', home: 'Phoenix', born: '1923', ops: '.797')
az.players.create(name: 'Andre Ethier', position: 'LF', home: 'Phoenix', born: '1982', ops: '.832')
az.players.create(name: 'Hank Leiber', position: 'CF', home: 'Phoenix', born: '1911', ops: '.813')
az.players.create(name: 'Chris Duncan', position: 'RF', home: 'Tucson', born: '1981', ops: '.806')

ar = Team.create(map_id: 5, state_code: 'AR', name: 'Arkansas', nickname: 'Mockingbirds')

ca = Team.create(map_id: 6, state_code: 'CA', name: 'California', nickname: 'Valley Quails', park_image: '/images/parks/ca.png')
ca.players.create(name: 'Ernie Lombardi', position: 'C', home: 'Oakland', born: '1908', ops: '.817')
ca.players.create(name: 'Mark McGwire', position: '1B', home: 'Pomona', born: '1963', ops: '.982')
ca.players.create(name: 'Chase Utley', position: '2B', home: 'Pasadena', born: '1978', ops: '.870')
ca.players.create(name: 'Evan Longoria', position: '3B', home: 'Downey', born: '1985', ops: '.870')
ca.players.create(name: 'Nomar Garciaparra', position: 'SS', home: 'Whittier', born: '1973', ops: '.882')
ca.players.create(name: 'Ted Williams', position: 'LF', home: 'San Diego', born: '1918', ops: '1.115')
ca.players.create(name: 'Barry Bonds', position: 'CF', home: 'Riverside', born: '1964', ops: '1.051')
ca.players.create(name: 'Joe DiMaggio', position: 'RF', home: 'Martinez', born: '1914', ops: '.976')


co = Team.create(map_id: 8, state_code: 'CO', name: 'Colorado', nickname: 'Lark Buntings')
ct = Team.create(map_id: 9, state_code: 'CT', name: 'Connecticut', nickname: 'Robins')
de = Team.create(map_id: 10, state_code: 'DE', name: 'Delaware', nickname: 'Blue Hen Chickens')

fl = Team.create(map_id: 12, state_code: 'FL', name: 'Florida', nickname: 'Mockingbirds', park_image: '/images/parks/fl.png')
fl.players.create(name: 'Mike Napoli', position: 'C', home: 'Hollywood', born: '1981', ops: '.859')
fl.players.create(name: 'Fred McGriff', position: '1B', home: 'Tampa', born: '1963', ops: '.886')
fl.players.create(name: 'Rickie Weeks', position: '2B', home: 'Daytona Beach', born: '1982', ops: '.768')
fl.players.create(name: 'Chipper Jones', position: '3B', home: 'DeLand', born: '1972', ops: '.930')
fl.players.create(name: 'Jay Bell', position: 'SS', home: 'Eglin A.F.B.', born: '1965', ops: '.753')
fl.players.create(name: 'Gary Sheffield', position: 'LF', home: 'Tampa', born: '1968', ops: '.907')
fl.players.create(name: 'Andrew McCutchen', position: 'CF', home: 'Fort Meade', born: '1986', ops: '.869')
fl.players.create(name: 'Luis Gonzalez', position: 'RF', home: 'Tampa', born: '1967', ops: '.845')

ga = Team.create(map_id: 13, state_code: 'GA', name: 'Georgia', nickname: 'Brown Thrashers', park_image: '/images/parks/ga.png')
ga.players.create(name: 'Buster Posey', position: 'C', home: 'Leesburg', born: '1987', ops: '.864')
ga.players.create(name: 'Johnny Mize', position: '1B', home: 'Demorest', born: '1913', ops: '.958')
ga.players.create(name: 'Jackie Robinson', position: '2B', home: 'Cairo', born: '1919', ops: '.875')
ga.players.create(name: 'Russel Branyon', position: '3B', home: 'Warner Robins', born: '1975', ops: '.813')
ga.players.create(name: 'Cecil Travis', position: 'SS', home: 'Riverdale', born: '1913', ops: '.782')
ga.players.create(name: 'Ty Cobb', position: 'LF', home: 'Narrows', born: '1886', ops: '.935')
ga.players.create(name: 'Moises Alou', position: 'CF', home: 'Atlanta', born: '1966', ops: '.887')
ga.players.create(name: 'JD Drew', position: 'RF', home: 'Valdosta', born: '1975', ops: '.872')

Team.create(map_id: 15, state_code: 'HI', name: 'Hawaii', nickname: 'Nenes')
Team.create(map_id: 16, state_code: 'ID', name: 'Idaho', nickname: 'Mountain Bluebirds')
Team.create(map_id: 17, state_code: 'IL', name: 'Illinois', nickname: 'Cardinals')
Team.create(map_id: 18, state_code: 'IN', name: 'Indiana', nickname: 'Cardinals')
Team.create(map_id: 19, state_code: 'IA', name: 'Iowa', nickname: 'Eastern Goldfinchs')
Team.create(map_id: 20, state_code: 'KS', name: 'Kansas', nickname: 'Western Meadowlarks')
Team.create(map_id: 21, state_code: 'KY', name: 'Kentucky', nickname: 'Cardinals')
Team.create(map_id: 22, state_code: 'LA', name: 'Louisiana', nickname: 'Eastern Brown Pelicans')

me = Team.create(map_id: 23, state_code: 'ME', name: 'Maine', nickname: 'Chickadees', park_image: '/images/parks/me.png')
me.players.create(name: 'Clyde Sukeforth', position: 'C', home: 'Washington', born: '1901', ops: '.644')
me.players.create(name: 'Del Bissonette', position: '1B', home: 'Winthrop', born: '1899', ops: '.852')
me.players.create(name: 'Ryan Flaherty', position: '2B', home: 'Portland', born: '1986', ops: '.655')
me.players.create(name: 'Harry Lord', position: '3B', home: 'Porter', born: '1882', ops: '.669')
me.players.create(name: 'Ben Nickerson', position: 'SS', home: 'Boothbay', born: '1986', ops: '.835')
me.players.create(name: 'George Gore', position: 'LF', home: 'Saccarappa', born: '1857', ops: '.797')
me.players.create(name: 'Walter Thornton', position: 'CF', home: 'Lewiston', born: '1875', ops: '.767')
me.players.create(name: 'Chief Sockalexis', position: 'RF', home: 'Old Town', born: '1871', ops: '.766')

Team.create(map_id: 24, state_code: 'MD', name: 'Maryland', nickname: 'Baltimore Orioles')

ma = Team.create(map_id: 25, state_code: 'MA', name: 'Massachusetts', nickname: 'Chickadees', park_image: '/images/parks/ma.png')
ma.players.create(name: 'Mickey Cochrane', position: 'C', home: 'Bridgewater', born: '1903', ops: '.887')
ma.players.create(name: 'Jeff Bagwell', position: '1B', home: 'Boston', born: '1968', ops: '.948')
ma.players.create(name: 'Mark Bellhorn', position: '2B', home: 'Boston', born: '1974', ops: '.734')
ma.players.create(name: 'Richie Hebner', position: '3B', home: 'Boston', born: '1947', ops: '.788')
ma.players.create(name: 'Joe Sullivan', position: 'SS', home: 'Charlestown', born: '1870', ops: '.740')
ma.players.create(name: 'Joe Kelley', position: 'LF', home: 'Cambridge', born: '1871', ops: '.847')
ma.players.create(name: 'Jimmy Bannon', position: 'CF', home: 'Amesbury', born: '1871', ops: '.832')
ma.players.create(name: 'Jimmy Ryan', position: 'RF', home: 'Clinton', born: '1863', ops: '.816')

Team.create(map_id: 26, state_code: 'MI', name: 'Michigan', nickname: 'Robins')
Team.create(map_id: 27, state_code: 'MN', name: 'Minnesota', nickname: 'Common Loons')
Team.create(map_id: 28, state_code: 'MS', name: 'Mississippi', nickname: 'Mockingbirds')
Team.create(map_id: 29, state_code: 'MO', name: 'Missouri', nickname: 'Bluebirds')
Team.create(map_id: 30, state_code: 'MT', name: 'Montana', nickname: 'Western Meadowlarks')
Team.create(map_id: 31, state_code: 'NE', name: 'Nebraska', nickname: 'Western Meadowlarks')
Team.create(map_id: 32, state_code: 'NV', name: 'Nevada', nickname: 'Mountain Bluebirds')
Team.create(map_id: 33, state_code: 'NH', name: 'New Hampshire', nickname: 'Purple Finchs')
Team.create(map_id: 34, state_code: 'NJ', name: 'New Jersey', nickname: 'Eastern Goldfinchs')
Team.create(map_id: 35, state_code: 'NM', name: 'New Mexico', nickname: 'Roadrunners')

ny = Team.create(map_id: 36, state_code: 'NY', name: 'New York', nickname: 'Bluebirds', park_image: '/images/parks/ny.png')
ny.players.create(name: 'Joe Torre', position: 'C', home: 'Brooklyn', born: '1940', ops: '.816')
ny.players.create(name: 'Lou Gehrig', position: '1B', home: 'New York', born: '1903', ops: '1.075')
ny.players.create(name: 'Ross Barnes', position: '2B', home: 'Mount Morris', born: '1850', ops: '.852')
ny.players.create(name: 'John McGraw', position: '3B', home: 'Truxton', born: '1873', ops: '.873')
ny.players.create(name: 'Alex Rodriguez', position: 'SS', home: 'New York', born: '1975', ops: '.941')
ny.players.create(name: 'Babe Herman', position: 'LF', home: 'Buffalo', born: '1903', ops: '.909')
ny.players.create(name: 'Rocky Colavito', position: 'CF', home: 'New York', born: '1933', ops: '.847')
ny.players.create(name: 'Hack Miller', position: 'RF', home: 'New York', born: '1894', ops: '.846')

Team.create(map_id: 37, state_code: 'NC', name: 'North Carolina', nickname: 'Cardinals')
Team.create(map_id: 38, state_code: 'ND', name: 'North Dakota', nickname: 'Western Meadowlarks')
Team.create(map_id: 39, state_code: 'OH', name: 'Ohio', nickname: 'Cardinals')
Team.create(map_id: 40, state_code: 'OK', name: 'Oklahoma', nickname: 'Scissor-tailed Flycatchers')
Team.create(map_id: 41, state_code: 'OR', name: 'Oregon', nickname: 'Western Meadowlarks')
Team.create(map_id: 42, state_code: 'PA', name: 'Pennsylvania', nickname: 'Ruffed Grouse')
Team.create(map_id: 44, state_code: 'RI', name: 'Rhode Island', nickname: 'Rhode Island Reds')
Team.create(map_id: 45, state_code: 'SC', name: 'South Carolina', nickname: 'Great Carolina Wrens')
Team.create(map_id: 46, state_code: 'SD', name: 'South Dakota', nickname: 'Ring-necked Pheasants')
Team.create(map_id: 47, state_code: 'TN', name: 'Tennessee', nickname: 'Mockingbirds')

tx = Team.create(map_id: 48, state_code: 'TX', name: 'Texas', nickname: 'Mockingbirds', park_image: '/images/parks/tex.png')
tx.players.create(name: 'Eddie Taubensee', position: 'C', home: 'Beeville', born: '1968', ops: '.760')
tx.players.create(name: 'Norm Cash', position: '1B', home: 'Justiceburg', born: '1934', ops: '.862')
tx.players.create(name: 'Rogers Hornsby', position: '2B', home: 'Winters', born: '1896', ops: '1.000')
tx.players.create(name: 'Eddie Mathews', position: '3B', home: 'Texarkana', born: '1931', ops: '.884')
tx.players.create(name: 'Topper Rigney', position: 'SS', home: 'Groveton', born: '1897', ops: '.756')
tx.players.create(name: 'Lance Berkman', position: 'LF', home: 'Waco', born: '1976', ops: '.943')
tx.players.create(name: 'Frank Robinson', position: 'CF', home: 'Beaumont', born: '1935', ops: '.925')
tx.players.create(name: 'Tris Speaker', position: 'RF', home: 'Hubbard', born: '1888', ops: '.917')

Team.create(map_id: 49, state_code: 'UT', name: 'Utah', nickname: 'Common American Gulls')
Team.create(map_id: 50, state_code: 'VT', name: 'Vermont', nickname: 'Hermit Thrushes')
Team.create(map_id: 51, state_code: 'VA', name: 'Virginia', nickname: 'Cardinals')
Team.create(map_id: 53, state_code: 'WA', name: 'Washington', nickname: 'Willow Goldfinchs')
Team.create(map_id: 54, state_code: 'WV', name: 'West Virginia', nickname: 'Cardinals')
Team.create(map_id: 55, state_code: 'WI', name: 'Wisconsin', nickname: 'Robins')
Team.create(map_id: 56, state_code: 'WY', name: 'Wyoming', nickname: 'Western Meadowlarks')
