/*global App, DS */

App.Team = DS.Model.extend({
  code: DS.attr('string'),
  name: DS.attr('string'),
  nickname: DS.attr('string'),
  // players: DS.hasMany('player')
  players: DS.attr()
});

App.Team.FIXTURES = [
  {map_id: 1, id: 'AL', name: 'Alabama', nickname: 'Yellowhammers'},
  {map_id: 2, id: 'AK', name: 'Alaska', nickname: 'Willow Ptarmigans'},
  {map_id: 4, id: 'AZ', name: 'Arizona', nickname: 'Cactus Wrens'},
  {map_id: 5, id: 'AR', name: 'Arkansas', nickname: 'Mockingbirds'},
  {map_id: 6, id: 'CA', name: 'California', nickname: 'Valley Quails', players: [
    {name: 'Ernie Lombardi', position: 'C', team: 'CA', home: 'Oakland', born: '1908', ops: '0.8172'},
    {name: 'Mark McGwire', position: '1B', team: 'CA', home: 'Pomona', born: '1963', ops: '0.9822'},
    {name: 'Chase Utley', position: '2B', team: 'CA', home: 'Pasadena', born: '1978', ops: '0.8707'},
    {name: 'Evan Longoria', position: '3B', team: 'CA', home: 'Downey', born: '1985', ops: '0.8696'},
    {name: 'Nomar Garciaparra', position: 'SS', team: 'CA', home: 'Whittier', born: '1973', ops: '0.8818'},
    {name: 'Ted Williams', position: 'LF', team: 'CA', home: 'San Diego', born: '1918', ops: '1.1153'},
    {name: 'Barry Bonds', position: 'CF', team: 'CA', home: 'Riverside', born: '1964', ops: '1.0510'},
    {name: 'Joe DiMaggio', position: 'RF', team: 'CA', home: 'Martinez', born: '1914', ops: '0.9764'},
  ]},
  {map_id: 8, id: 'CO', name: 'Colorado', nickname: 'Lark Buntings'},
  {map_id: 9, id: 'CT', name: 'Connecticut', nickname: 'Robins'},
  {map_id: 10, id: 'DE', name: 'Delaware', nickname: 'Blue Hen Chickens'},
  {map_id: 12, id: 'FL', name: 'Florida', nickname: 'Mockingbirds'},
  {map_id: 13, id: 'GA', name: 'Georgia', nickname: 'Brown Thrashers'},
  {map_id: 15, id: 'HI', name: 'Hawaii', nickname: 'Nenes'},
  {map_id: 16, id: 'ID', name: 'Idaho', nickname: 'Mountain Bluebirds'},
  {map_id: 17, id: 'IL', name: 'Illinois', nickname: 'Cardinals'},
  {map_id: 18, id: 'IN', name: 'Indiana', nickname: 'Cardinals'},
  {map_id: 19, id: 'IA', name: 'Iowa', nickname: 'Eastern Goldfinchs'},
  {map_id: 20, id: 'KS', name: 'Kansas', nickname: 'Western Meadowlarks'},
  {map_id: 21, id: 'KY', name: 'Kentucky', nickname: 'Cardinals'},
  {map_id: 22, id: 'LA', name: 'Louisiana', nickname: 'Eastern Brown Pelicans'},
  {map_id: 23, id: 'ME', name: 'Maine', nickname: 'Chickadees', players: [{name: 'Clyde Sukeforth', position: 'C', team: 'ME', home: 'Washington', born: '1901', ops: '.644'}, {name: 'Del Bissonette', position: '1B', team: 'ME', home: 'Winthrop', born: '1899', ops: '.852'},{name: 'Ryan Flaherty', position: '2B', team: 'ME', home: 'Portland', born: '1986', ops: '.655'},{name: 'Harry Lord', position: '3B', team: 'ME', home: 'Porter', born: '1882', ops: '.669'},{name: 'Ben Nickerson', position: 'SS', team: 'ME', home: 'Boothbay', born: '1986', ops: '.835'},{name: 'George Gore', position: 'LF', team: 'ME', home: 'Saccarappa', born: '1857', ops: '.797'},{name: 'Walter Thornton', position: 'CF', team: 'ME', home: 'Lewiston', born: '1875', ops: '.767'},{name: 'Chief Sockalexis', position: 'RF', team: 'ME', home: 'Old Town', born: '1871', ops: '.766'},]},
  {map_id: 24, id: 'MD', name: 'Maryland', nickname: 'Baltimore Orioles'},
  {map_id: 25, id: 'MA', name: 'Massachusetts', nickname: 'Chickadees'},
  {map_id: 26, id: 'MI', name: 'Michigan', nickname: 'Robins'},
  {map_id: 27, id: 'MN', name: 'Minnesota', nickname: 'Common Loons'},
  {map_id: 28, id: 'MS', name: 'Mississippi', nickname: 'Mockingbirds'},
  {map_id: 29, id: 'MO', name: 'Missouri', nickname: 'Bluebirds'},
  {map_id: 30, id: 'MT', name: 'Montana', nickname: 'Western Meadowlarks'},
  {map_id: 31, id: 'NE', name: 'Nebraska', nickname: 'Western Meadowlarks'},
  {map_id: 32, id: 'NV', name: 'Nevada', nickname: 'Mountain Bluebirds'},
  {map_id: 33, id: 'NH', name: 'New Hampshire', nickname: 'Purple Finchs'},
  {map_id: 34, id: 'NJ', name: 'New Jersey', nickname: 'Eastern Goldfinchs'},
  {map_id: 35, id: 'NM', name: 'New Mexico', nickname: 'Roadrunners'},
  {map_id: 36, id: 'NY', name: 'New York', nickname: 'Bluebirds'},
  {map_id: 37, id: 'NC', name: 'North Carolina', nickname: 'Cardinals'},
  {map_id: 38, id: 'ND', name: 'North Dakota', nickname: 'Western Meadowlarks'},
  {map_id: 39, id: 'OH', name: 'Ohio', nickname: 'Cardinals'},
  {map_id: 40, id: 'OK', name: 'Oklahoma', nickname: 'Scissor-tailed Flycatchers'},
  {map_id: 41, id: 'OR', name: 'Oregon', nickname: 'Western Meadowlarks'},
  {map_id: 42, id: 'PA', name: 'Pennsylvania', nickname: 'Ruffed Grouse'},
  {map_id: 44, id: 'RI', name: 'Rhode Island', nickname: 'Rhode Island Reds'},
  {map_id: 45, id: 'SC', name: 'South Carolina', nickname: 'Great Carolina Wrens'},
  {map_id: 46, id: 'SD', name: 'South Dakota', nickname: 'Ring-necked Pheasants'},
  {map_id: 47, id: 'TN', name: 'Tennessee', nickname: 'Mockingbirds'},
  {map_id: 48, id: 'TX', name: 'Texas', nickname: 'Mockingbirds', players: [
    {name: 'Eddie Taubensee', position: 'C', team: 'TX', home: 'Beeville', born: '1968', ops: '0.7595'},
    {name: 'Norm Cash', position: '1B', team: 'TX', home: 'Justiceburg', born: '1934', ops: '0.8616'},
    {name: 'Rogers Hornsby', position: '2B', team: 'TX', home: 'Winters', born: '1896', ops: '1.0004'},
    {name: 'Eddie Mathews', position: '3B', team: 'TX', home: 'Texarkana', born: '1931', ops: '0.8841'},
    {name: 'Topper Rigney', position: 'SS', team: 'TX', home: 'Groveton', born: '1897', ops: '0.7564'},
    {name: 'Lance Berkman', position: 'LF', team: 'TX', home: 'Waco', born: '1976', ops: '0.9429'},
    {name: 'Frank Robinson', position: 'CF', team: 'TX', home: 'Beaumont', born: '1935', ops: '0.9254'},
    {name: 'Tris Speaker', position: 'RF', team: 'TX', home: 'Hubbard', born: '1888', ops: '0.9173'},
  ]},
  {map_id: 49, id: 'UT', name: 'Utah', nickname: 'Common American Gulls'},
  {map_id: 50, id: 'VT', name: 'Vermont', nickname: 'Hermit Thrushes'},
  {map_id: 51, id: 'VA', name: 'Virginia', nickname: 'Cardinals'},
  {map_id: 53, id: 'WA', name: 'Washington', nickname: 'Willow Goldfinchs'},
  {map_id: 54, id: 'WV', name: 'West Virginia', nickname: 'Cardinals'},
  {map_id: 55, id: 'WI', name: 'Wisconsin', nickname: 'Robins'},
  {map_id: 56, id: 'WY', name: 'Wyoming', nickname: 'Western Meadowlarks'}
];
