/*global App, DS */

App.Team = DS.Model.extend({
  code: DS.attr('string'),
  name: DS.attr('string'),
  nickname: DS.attr('string'),
  // players: DS.hasMany('player')
  players: DS.attr()
});

App.Team.FIXTURES = [
  {map_id: 1, id: 'AL', name: 'Alabama', nickname: 'Yellowhammers'},
  {map_id: 2, id: 'AK', name: 'Alaska', nickname: 'Willow Ptarmigans'},
  {map_id: 4, id: 'AZ', name: 'Arizona', nickname: 'Cactus Wrens'},
  {map_id: 5, id: 'AR', name: 'Arkansas', nickname: 'Mockingbirds'},
  {map_id: 6, id: 'CA', name: 'California', nickname: 'Valley Quails'},
  {map_id: 8, id: 'CO', name: 'Colorado', nickname: 'Lark Buntings'},
  {map_id: 9, id: 'CT', name: 'Connecticut', nickname: 'Robins'},
  {map_id: 10, id: 'DE', name: 'Delaware', nickname: 'Blue Hen Chickens'},
  {map_id: 12, id: 'FL', name: 'Florida', nickname: 'Mockingbirds'},
  {map_id: 13, id: 'GA', name: 'Georgia', nickname: 'Brown Thrashers'},
  {map_id: 15, id: 'HI', name: 'Hawaii', nickname: 'Nenes'},
  {map_id: 16, id: 'ID', name: 'Idaho', nickname: 'Mountain Bluebirds'},
  {map_id: 17, id: 'IL', name: 'Illinois', nickname: 'Cardinals'},
  {map_id: 18, id: 'IN', name: 'Indiana', nickname: 'Cardinals'},
  {map_id: 19, id: 'IA', name: 'Iowa', nickname: 'Eastern Goldfinchs'},
  {map_id: 20, id: 'KS', name: 'Kansas', nickname: 'Western Meadowlarks'},
  {map_id: 21, id: 'KY', name: 'Kentucky', nickname: 'Cardinals'},
  {map_id: 22, id: 'LA', name: 'Louisiana', nickname: 'Eastern Brown Pelicans'},
  {map_id: 23, id: 'ME', name: 'Maine', nickname: 'Chickadees', players: [{name: 'John Doe', position: '1B', team: 'ME'}, {name: 'John Lacky', position: '2B', team: 'ME'}]},
  {map_id: 24, id: 'MD', name: 'Maryland', nickname: 'Baltimore Orioles'},
  {map_id: 25, id: 'MA', name: 'Massachusetts', nickname: 'Chickadees'},
  {map_id: 26, id: 'MI', name: 'Michigan', nickname: 'Robins'},
  {map_id: 27, id: 'MN', name: 'Minnesota', nickname: 'Common Loons'},
  {map_id: 28, id: 'MS', name: 'Mississippi', nickname: 'Mockingbirds'},
  {map_id: 29, id: 'MO', name: 'Missouri', nickname: 'Bluebirds'},
  {map_id: 30, id: 'MT', name: 'Montana', nickname: 'Western Meadowlarks'},
  {map_id: 31, id: 'NE', name: 'Nebraska', nickname: 'Western Meadowlarks'},
  {map_id: 32, id: 'NV', name: 'Nevada', nickname: 'Mountain Bluebirds'},
  {map_id: 33, id: 'NH', name: 'New Hampshire', nickname: 'Purple Finchs'},
  {map_id: 34, id: 'NJ', name: 'New Jersey', nickname: 'Eastern Goldfinchs'},
  {map_id: 35, id: 'NM', name: 'New Mexico', nickname: 'Roadrunners'},
  {map_id: 36, id: 'NY', name: 'New York', nickname: 'Bluebirds'},
  {map_id: 37, id: 'NC', name: 'North Carolina', nickname: 'Cardinals'},
  {map_id: 38, id: 'ND', name: 'North Dakota', nickname: 'Western Meadowlarks'},
  {map_id: 39, id: 'OH', name: 'Ohio', nickname: 'Cardinals'},
  {map_id: 40, id: 'OK', name: 'Oklahoma', nickname: 'Scissor-tailed Flycatchers'},
  {map_id: 41, id: 'OR', name: 'Oregon', nickname: 'Western Meadowlarks'},
  {map_id: 42, id: 'PA', name: 'Pennsylvania', nickname: 'Ruffed Grouse'},
  {map_id: 44, id: 'RI', name: 'Rhode Island', nickname: 'Rhode Island Reds'},
  {map_id: 45, id: 'SC', name: 'South Carolina', nickname: 'Great Carolina Wrens'},
  {map_id: 46, id: 'SD', name: 'South Dakota', nickname: 'Ring-necked Pheasants'},
  {map_id: 47, id: 'TN', name: 'Tennessee', nickname: 'Mockingbirds'},
  {map_id: 48, id: 'TX', name: 'Texas', nickname: 'Mockingbirds'},
  {map_id: 49, id: 'UT', name: 'Utah', nickname: 'Common American Gulls'},
  {map_id: 50, id: 'VT', name: 'Vermont', nickname: 'Hermit Thrushes'},
  {map_id: 51, id: 'VA', name: 'Virginia', nickname: 'Cardinals'},
  {map_id: 53, id: 'WA', name: 'Washington', nickname: 'Willow Goldfinchs'},
  {map_id: 54, id: 'WV', name: 'West Virginia', nickname: 'Cardinals'},
  {map_id: 55, id: 'WI', name: 'Wisconsin', nickname: 'Robins'},
  {map_id: 56, id: 'WY', name: 'Wyoming', nickname: 'Western Meadowlarks'}
];
